### ISSUE TITLE
License and maintenance plans

### ISSUE THREAD

**Issue by alxthm** [prratek/tap-twitter#4]
Thanks for building this tap! I would be interesting in using it (mostly for the Users stream) and making contributions.

There is no license in the repo however ([only the default Apache 2.0 in `pyproject.toml`](https://github.com/prratek/tap-twitter/blob/b355bf6cf82e6c212585b9f80bc2871194b5ec1b/pyproject.toml#L10)), so I was wondering if you were planning on adding one?

Also, do you plan on maintaining this tap in the future? I think it would be a very nice addition to the [Meltano Extractors hub](https://hub.meltano.com/extractors/). As far as I know, the [main twitter tap listed there](https://hub.meltano.com/taps/twitter) does not seem very active, does not use the meltano SDK, and uses the [python-twitter](https://github.com/bear/python-twitter) package instead of Twitter API v2.

**Comment by prratek** [comment]
> Thanks for building this tap! I would be interesting in using it (mostly for the Users stream) and making contributions.
> 
> There is no license in the repo however ([only the default Apache 2.0 in `pyproject.toml`](https://github.com/prratek/tap-twitter/blob/b355bf6cf82e6c212585b9f80bc2871194b5ec1b/pyproject.toml#L10)), so I was wondering if you were planning on adding one?
> 
> Also, do you plan on maintaining this tap in the future? I think it would be a very nice addition to the [Meltano Extractors hub](https://hub.meltano.com/extractors/). As far as I know, the [main twitter tap listed there](https://hub.meltano.com/taps/twitter) does not seem very active, does not use the meltano SDK, and uses the [python-twitter](https://github.com/bear/python-twitter) package instead of Twitter API v2.

Hi @alxthm - I work at Vox Media and we're talking about consolidating a few different Singer taps under the `voxmedia` GitHub org with an open source license. We use this tap in production today with Meltano and so the plan definitely is to keep maintaining it and we welcome any contributions if you spot issues - I'll make a PR to add it to the Hub along with a couple others once we've moved it to the other GitHub org, hopefully later this month.

**Comment by alxthm** [comment]
Good to hear, I am looking forward to your release then ! :)

**Comment by prratek** [comment]
Hey @alxthm, the Twitter tap is now public [here](https://github.com/voxmedia/tap-twitter) within the `voxmedia` GitHub org with an Apache license. Going to add it to the hub shortly and then eventually deprecate this repo. Any contributions or issues on the new one are welcome!
